version: '2.0'
 
services:

  eureka-user-9990:
    image: registry.cn-qingdao.aliyuncs.com/woaipaifang-product/eureka-user:1.0.4.RELEASES
    restart: always
    container_name: eureka-user-9990
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9990:9990
    entrypoint: java -jar -Dserver.port=9990 /eureka-user-1.0.4.RELEASES.jar

  nginx-eureka-user-9999:
    image: registry.cn-qingdao.aliyuncs.com/woaipaifang-management/nginx:1.5.8
    restart: always
    container_name: nginx-eureka-user-9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /microservice-user/eureka-user/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /microservice-user/eureka-user/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 9999:9999
